version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: skill-record-processor_zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: skill-record-processor_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "backgroundjob.sync.user.skills:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
