version: '3'
services:
  ubahn-skill-record-processor:
    image: ubahn-skill-record-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
